import os
from typing import List, Dict, Any
from qdrant_client import QdrantClient, models

class VectorStoreManager:
    """
    Manages the Qdrant Vector Database, handling the schema definition for 
    Dense and Sparse vectors, and enforcing RBAC at the DB level.
    """
    
    def __init__(self, collection_name: str = "enterprise_codebase"):
        self.collection_name = collection_name
        # Default to local memory/disk if no URL provided (for local dev)
        qdrant_url = os.getenv("QDRANT_URL", ":memory:")
        api_key = os.getenv("QDRANT_API_KEY")
        
        if qdrant_url == ":memory:":
            self.client = QdrantClient(qdrant_url)
        else:
            self.client = QdrantClient(url=qdrant_url, api_key=api_key)
            
        self._ensure_collection_exists()

    def _ensure_collection_exists(self):
        """Creates the collection with Dense and Sparse configurations if it doesn't exist."""
        if not self.client.collection_exists(self.collection_name):
            self.client.create_collection(
                collection_name=self.collection_name,
                # Dense vectors from Voyage AI code-3 (1024 dims)
                vectors_config={
                    "dense": models.VectorParams(
                        size=1024, 
                        distance=models.Distance.COSINE
                    )
                },
                # Sparse vectors configuration
                sparse_vectors_config={
                    "sparse": models.SparseVectorParams(
                        modifier=models.Modifier.IDF
                    )
                }
            )
            
            # CRITICAL: Create a payload index for our RBAC field `allowed_groups`
            # This ensures filtering by department/role is extremely fast
            self.client.create_payload_index(
                collection_name=self.collection_name,
                field_name="allowed_groups",
                field_schema=models.PayloadSchemaType.KEYWORD
            )
            print(f"Created Qdrant collection: {self.collection_name}")

    def upsert_chunks(self, chunks: List[Dict[str, Any]], repo_name: str, allowed_groups: List[str]):
        """
        Loads processed chunks into Qdrant.
        """
        points = []
        for i, chunk in enumerate(chunks):
            # We use the AST hash as part of the point ID to manage incremental updates
            # In production, we'd hash (repo_name + file_path + ast_hash) to an integer/UUID
            point_id = hash(f"{repo_name}_{chunk.get('hash', str(i))}") & ((1<<63)-1) # Positive int64
            
            payload = {
                "repo_name": repo_name,
                "type": chunk.get("type", "unknown"),
                "content": chunk.get("content", ""),
                "summary": chunk.get("summary", ""),
                "start_line": chunk.get("start_line", 0),
                "end_line": chunk.get("end_line", 0),
                "ast_hash": chunk.get("hash", ""),
                "allowed_groups": allowed_groups  # <--- Core RBAC mechanism
            }
            
            points.append(
                models.PointStruct(
                    id=point_id,
                    vector={
                        "dense": chunk.get("dense_embedding", [0.0]*1024)
                        # We would add 'sparse' vectors here if generated by FastEmbed
                    },
                    payload=payload
                )
            )
            
        if points:
            self.client.upsert(
                collection_name=self.collection_name,
                points=points
            )
            print(f"Upserted {len(points)} chunks into Qdrant.")

if __name__ == "__main__":
    # Smoke Test
    db = VectorStoreManager()
    dummy_chunks = [{
        "content": "def test(): pass",
        "hash": "somehash123",
        "dense_embedding": [0.1] * 1024
    }]
    db.upsert_chunks(dummy_chunks, repo_name="frontend-app", allowed_groups=["engineering_team"])
